version: "3"

services:
  mysql-local:
    platform: linux/x86_64
    image: mysql:5.7.35
    container_name: mysql-local-esc
    restart: always
    volumes:
      - ./data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
